### ISSUE TITLE
[Request] Ignore Pastes or Tildes

### ISSUE THREAD

**Issue by livejamie** [JonasRock/POETradeFuzzySearch#5]
I like to copy-paste certain mods, and the addon adds an extra tilde at the start to pastes that already include one, breaking the search.

It would be nice if the addon could detect a paste (ideal) or if the paste contains a tilde already.

Thanks!

**Comment by JonasRock** [comment]
Hi,

the issue with copy-pasting was that the addon activated already upon pressing CTRL when pasting and then inserted the tilde.
I'm uploading a version right now that does not add the tilde if the query is empty, as when pressing any modifier keys. This also prevents adding another tilde when copy-pasting.

Hopefully this should fix your issue (Might take a day or so for the webstore versions to update).
